### ISSUE TITLE
Add a YouTube link in the movie's landing page for its trailer

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/test-app#1]
Hello Praveen,

I am planning to create static data for 5-10 movies and including the Youtube trailer link in the data as current data doesn't have Youtube source link. I will create the static data in backend and still uses the API calls to fetch the data from backend.

**Comment by praveenpuglia** [comment]
@talatam143 Can you check if there are other open source data bases that provide this? may be we can use a different dataset to build it?

**Comment by talatam143** [comment]
@praveenpuglia  I have checked TMDB API, where we can get all details about movie, I am planning to use it. We can connect and check further more about the api

**Comment by talatam143** [comment]
@praveenpuglia As discussed proceeding to use the TMDB API, to build MFlix project further.

**Comment by praveenpuglia** [comment]
Cool!

**Comment by praveenpuglia** [comment]
Whenever you are ready with your changes, please send a PR.

**Comment by talatam143** [comment]
Hello @praveenpuglia ,

I have developed the trailer component in the movie page and changed the Mongo DB database to TMDB api in the following PR    #3

**Comment by praveenpuglia** [comment]
Closed by #5
